# Generated by Django 4.1.7 on 2023-05-19 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('higiseg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(max_length=255)),
                ('descricaoFuncionario', models.CharField(blank=True, max_length=255, null=True)),
                ('idadeFuncionario', models.CharField(blank=True, max_length=4, null=True)),
                ('sexoFuncionario', models.CharField(blank=True, max_length=2, null=True)),
                ('userClienteFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_idClienteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=255)),
                ('idClienteWeb', models.CharField(max_length=4)),
                ('userCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAgendamento', models.DateTimeField()),
                ('horarioAgendamento', models.TimeField()),
                ('funcionarioAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='higiseg.funcionario')),
                ('userAdminAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
