# Generated by Django 4.1.7 on 2023-05-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higiseg', '0002_funcionario_cliente_idclienteweb_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='horarioAgendamento',
        ),
    ]
